/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author Viki
 */
public class Calculation extends javax.swing.JFrame {

    /**
     * Creates new form Calculation
     */
    public Calculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Enter Current Reading :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, 40));
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Amount to Pay :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 40));
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 150, 40));

        jButton1.setText("Claculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 110, 40));

        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 90, 40));

        jLabel3.setText("Rs.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        setSize(new java.awt.Dimension(800, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Option ob=new Option();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ArrayList<UserDetails> B;
        
        try{
        FileInputStream fi1=new FileInputStream("User.tmp");
        ObjectInputStream o1 =new ObjectInputStream(fi1);
        B=(ArrayList<UserDetails>) o1.readObject();

        o1.close();
        fi1.close();
        }
        catch(Exception e)
        {
                B=new ArrayList<UserDetails>();
        }
        
        ArrayList<Index> arr;
        try{
        FileInputStream fi11=new FileInputStream("Number.tmp");
        ObjectInputStream o11 =new ObjectInputStream(fi11);
        arr=(ArrayList<Index>) o11.readObject();

        o11.close();
        fi11.close();
        }
        catch(Exception e)
        {
                arr=new ArrayList<Index>();
        }
        
        Index temp=new Index();
        temp=arr.get(0);
        
        UserDetails obj=B.get(temp.ind);
        obj.setCur(Double.parseDouble(a.getText()));
        double Billamt=0;
        if(obj.getCtype().equals("Domestic")||obj.getCtype().equals("Home")||obj.getCtype().equals("domestic")||obj.getCtype().equals("home"))
        {
            double units = obj.getCur()-obj.getPre();
            if(units<=100)
                    Billamt=units*1.0;
            else if(units<=200)
                    Billamt=100*1+(units-100)*2.50;
            else if(units<=500)
                    Billamt=100*1+100*2.50+(units-200)*4;
            else
                    Billamt=100*1+100*2.50+500*4+(units-500)*6;
        }
        else if(obj.getCtype().equals("Commercial")||obj.getCtype().equals("commercial"))
        {
            double units=obj.getCur()-obj.getPre();
            if(units<=100)
                    Billamt=units*2;
            else if(units<=200)
                    Billamt=100*2+(units-100)*4.50;
            else if(units<=500)
                    Billamt=100*2+100*4.50+(units-200)*6;
            else
                    Billamt=100*2+100*4.50+500*6+(units-500)*7;
        }
        obj.History.add(Billamt);
        b.setText(Double.toString(Billamt));
        B.set(temp.ind,obj);
        
        try{
            FileOutputStream fi=new FileOutputStream("User.tmp");
            ObjectOutputStream o =new ObjectOutputStream(fi);

            o.writeObject(B);
            
            o.close();
            fi.close();
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
