/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Viki
 */
class Index implements Serializable
{
    int ind;
}

public class Page1_1 extends javax.swing.JFrame {

    /**
     * Creates new form Page1_1
     */
    public Page1_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_name1 = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        login1 = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 230, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("User Id :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 113, 39));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));
        getContentPane().add(user_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 160, 30));
        getContentPane().add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 160, 30));

        login1.setText("Login");
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        getContentPane().add(login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 100, 40));

        exit1.setText("Exit");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 80, 40));

        setSize(new java.awt.Dimension(800, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:
        ArrayList<UserDetails> B;
        
        try{
        FileInputStream fi1=new FileInputStream("User.tmp");
        ObjectInputStream o1 =new ObjectInputStream(fi1);
        B=(ArrayList<UserDetails>) o1.readObject();

        o1.close();
        fi1.close();
        }
        catch(Exception e)
        {
                B=new ArrayList<UserDetails>();
        }
        
       String pass1=new String(password1.getPassword());
       String user1=new String(user_name1.getText());
       int flag=0,i;
       Index te=new Index();
       UserDetails obj = new UserDetails();
    for(i=0;i<B.size();i++)
    {
      
      obj=B.get(i);
      
        try
        {
             if(user1.equals(obj.getUserID()))
             {
               if(pass1.equals(obj.getPwd()))
               {
                     JOptionPane.showMessageDialog(this, "Login Successful");
                     te.ind=i;
                     flag=1;
                     break;
                }
             }
             else
             {
                 flag=0;
             }
        
       }
       catch(Exception e)
       {
       }
    }
     if(flag==0)
        {
            JOptionPane.showMessageDialog(this, "Invalid Username");
        }
    ArrayList<Index> a=new ArrayList<Index>();
    a.add(te);
    try{
    FileOutputStream fi=new FileOutputStream("Number.tmp");
    ObjectOutputStream o =new ObjectOutputStream(fi);

    o.writeObject(a);

    o.close();
    fi.close();
    }
    catch(Exception e)
    {
        //JOptionPane.showMessageDialog(this,"2 "+e);
    }
    if(flag==1)
    {
        this.dispose();
        Option ob=new Option();
        ob.setVisible(true);
    }
    }//GEN-LAST:event_login1ActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page1_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login1;
    private javax.swing.JPasswordField password1;
    private javax.swing.JTextField user_name1;
    // End of variables declaration//GEN-END:variables
}
